# Site settings
title: Paolo Rotolo's blog
email: paolorotolo@ubuntu.com
description: > # this means to ignore newlines until "baseurl:"
 Italian student, passionate about IT, and technology in general.
 I'm a big supporter of Open Source Software and an Ubuntu member.
 I like testing, coding and design new things.
 
 Lead developer at Numix Project Ltd. and Google + & Chrome Rising Star.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://paolorotolo.github.io" # the base hostname & protocol for your site
twitter_username: paolorotolo
github_username:  paolorotolo

# Build settings
markdown: kramdown
